// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class CierreDeCajaConfiguration : IEntityTypeConfiguration<CierreDeCaja>
    {
        public void Configure(EntityTypeBuilder<CierreDeCaja> entity)
        {
            entity.HasKey(e => e.IdCierre).HasName("PK_CierreDeCaja");


            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.CierreDeCaja)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_CierreDeCaja_Sucursales");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.CierreDeCaja)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_CierreDeCaja_Usuarios");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CierreDeCaja> entity);
    }
}
