// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class CierreDeCajaDetalleConfiguration : IEntityTypeConfiguration<CierreDeCajaDetalle>
    {
        public void Configure(EntityTypeBuilder<CierreDeCajaDetalle> entity)
        {
            entity.HasKey( e => new { e.IdCierre, e.IdDetalle } ).HasName("PK_CierreDeCajaDetalle");

            entity.Property(e => e.IdDetalle).ValueGeneratedOnAdd();


            entity.HasOne(d => d.IdCierreNavigation).WithMany(p => p.CierreDeCajaDetalle)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_CierreDeCaja_CierreDeCajaDetalle");

            entity.HasOne(d => d.IdTipoFormaPagoNavigation).WithMany(p => p.CierreDeCajaDetalle)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_CierreDeCajaDetalle_TipoFormasDePago");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CierreDeCajaDetalle> entity);
    }
}
