// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class ComprobanteConfiguration : IEntityTypeConfiguration<Comprobante>
    {
        public void Configure(EntityTypeBuilder<Comprobante> entity)
        {
            entity.HasKey(e => e.IdComprobante).HasName("PK_Comprobante");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.SucursalNavigation).WithMany(p => p.Comprobantes)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Comprobante_Sucursal");

            entity.HasOne(d => d.UsuarioNavigation).WithMany(p => p.Comprobantes)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Comprobante_Usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Comprobante> entity);
    }
}
