// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class CompraFormasDePagoConfiguration : IEntityTypeConfiguration<CompraFormasDePago>
    {
        public void Configure(EntityTypeBuilder<CompraFormasDePago> entity)
        {
            entity.HasKey(e => new { e.IdCompra, e.IdTipoFormaPago }).HasName("PK__ComprasF__F56901DBAD54FA8D");

            entity.HasOne(d => d.IdTipoFormaPagoNavigation).WithMany(p => p.CompraFormasDePago)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Compras_TipoFormaPago");

            entity.HasOne(d => d.IdCompraNavigation).WithMany(p => p.CompraFormasDePago)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Compras_CompraFormaPago");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CompraFormasDePago> entity);
    }
}
