// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class CompraConfiguration : IEntityTypeConfiguration<Compra>
    {
        public void Configure(EntityTypeBuilder<Compra> entity)
        {
            entity.HasKey(e => e.IdCompra).HasName("PK__Compras__0A5CDB5C2346FAF2");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Compras)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Compras__IdClien__1C5231C2");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Compras)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Compras__IdSucur__1B5E0D89");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Compras)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Compras__IdUsuar__1A69E950");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Compra> entity);
    }
}
