// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class CuentaCorrienteConfiguration : IEntityTypeConfiguration<CuentaCorriente>
    {
        public void Configure(EntityTypeBuilder<CuentaCorriente> entity)
        {
            entity.HasKey(e => e.IdCtacte).HasName("PK__CuentaCo__39D1A97F1760B16D");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IdTipoDeMovimiento).IsFixedLength();
            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdCierreNavigation).WithMany(p => p.CuentaCorrientes)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_CuentaCorriente_CierreDeCaja");  
            
            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.CuentaCorrientes)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__CuentaCor__IdSuc__4183B671");

            entity.HasOne(d => d.IdTipoDeMovimientoNavigation).WithMany(p => p.CuentaCorrientes)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__CuentaCor__IdTip__4277DAAA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CuentaCorriente> entity);
    }
}
