// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class GastoConfiguration : IEntityTypeConfiguration<Gasto>
    {
        public void Configure(EntityTypeBuilder<Gasto> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_Gasto");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Gasto)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Gasto_Sucursal");

            entity.HasOne(d => d.IdTipoDeGastoNavigation).WithMany(p => p.Gasto)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Gasto_TipoDeGasto");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Gasto)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Gasto_Usuario");


            entity.HasOne(d => d.IdTipoFormaPagoNavigation).WithMany(p => p.Gasto)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Gasto_FormaPago");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Gasto> entity);
    }
}
