// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class ParamAfipConfiguration : IEntityTypeConfiguration<ParamAfip>
    {
        public void Configure(EntityTypeBuilder<ParamAfip> entity)
        {
            entity.HasKey(e => e.IdSucursal).HasName("PK_ParamAfip");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParamAfip> entity);
    }
}
