// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class ProductoConfiguration : IEntityTypeConfiguration<Producto>
    {
        public void Configure(EntityTypeBuilder<Producto> entity)
        {
            entity.HasKey(e => e.IdProducto).HasName("PK__Producto__098892100A6A9AD0");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.Productos)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Producto_Estado");

            entity.HasOne(d => d.IdTipoProductoNavigation).WithMany(p => p.Productos)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Producto_TiposProducto");

            entity.HasOne(d => d.IdTipoTalleNavigation).WithMany(p => p.Productos)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Producto_TipoTalle");

            entity.HasOne(d => d.IdTipoMarcaNavigation).WithMany(p => p.Productos)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Producto_TipoMarca");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Productos)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Producto_Usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Producto> entity);
    }
}
