// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class ProductoEstadoConfiguration : IEntityTypeConfiguration<ProductoEstado>
    {
        public void Configure(EntityTypeBuilder<ProductoEstado> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Producto__3214EC272AD15D5E");

            entity.Property(e => e.FechaInicio).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FechaFin).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.ProductoEstado)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_EstadoP_Estado");

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.ProductoEstado)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_EstadoP_Producto");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.ProductoEstado)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_EstadoP_Usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductoEstado> entity);
    }
}
