// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class SessionConfiguration : IEntityTypeConfiguration<Session>
    {
        public void Configure(EntityTypeBuilder<Session> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Sessions__3214EC077E69A99B");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Sessions)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Sessions__IdUsua__6D6238AF");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Session> entity);
    }
}
