// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class TiposDeMovimientoConfiguration : IEntityTypeConfiguration<TiposDeMovimiento>
    {
        public void Configure(EntityTypeBuilder<TiposDeMovimiento> entity)
        {
            entity.HasKey(e => e.IdTipoDeMovimiento).HasName("PK__TiposDeM__983B1D084F987822");

            entity.Property(e => e.IdTipoDeMovimiento).IsFixedLength();
            entity.Property(e => e.Activo)
            .HasDefaultValueSql("('S')")
            .IsFixedLength();
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TiposDeMovimiento> entity);
    }
}
