// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class VentaFormasDePagoConfiguration : IEntityTypeConfiguration<VentaFormasDePago>
    {
        public void Configure(EntityTypeBuilder<VentaFormasDePago> entity)
        {
            entity.HasKey(e => new { e.IdVenta, e.IdTipoFormaPago }).HasName("PK__VentaFor__43279A3A1829B48C");

            entity.HasOne(d => d.IdTipoFormaPagoNavigation).WithMany(p => p.VentaFormasDePagos)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_VentaFormasDePago_TipoFormasDePago");

            entity.HasOne(d => d.IdVentaNavigation).WithMany(p => p.VentaFormasDePagos)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__VentaForm__IdVen__3429BB53");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VentaFormasDePago> entity);
    }
}
