// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class VentaConfiguration : IEntityTypeConfiguration<Venta>
    {
        public void Configure(EntityTypeBuilder<Venta> entity)
        {
            entity.HasKey(e => e.IdVenta).HasName("PK_Venta");

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ModifiedDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Venta)
            .HasForeignKey(d => d.IdCliente)
            .IsRequired(false)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Venta_Cliente");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Venta)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Venta_Sucursal");

            entity.HasOne(d => d.IdComprobanteNavigation).WithMany(p => p.Venta)
            .HasForeignKey(d => d.IdComprobante)
            .IsRequired(false)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Venta_Comprobante");
            
            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Venta)
            .HasForeignKey(d => d.IdUsuario)
            .IsRequired(false)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Venta_Usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Venta> entity);
    }
}
