// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Entities.Items;

namespace Data.Models.Configurations
{
    public partial class VentaDetalleConfiguration : IEntityTypeConfiguration<VentaDetalle>
    {
        public void Configure(EntityTypeBuilder<VentaDetalle> entity)
        {
            entity.HasKey(e => new { e.IdVenta, e.IdProducto }).HasName("PK__VentaDet__AC8AC99C4B8B6F4F");

            entity.Property(e => e.Cantidad).HasDefaultValueSql("((1))");

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.VentaDetalles)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_VentaDetalle_Producto");

            entity.HasOne(d => d.IdVentaNavigation).WithMany(p => p.VentaDetalles)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__VentaDeta__IdVen__2F650636");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VentaDetalle> entity);
    }
}
