// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Items;
using Microsoft.EntityFrameworkCore;


namespace Data.Models;

public partial class Maria_MCContext : DbContext
{
    public Maria_MCContext(DbContextOptions<Maria_MCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CierreDeCaja> CierreDeCaja { get; set; }
    public virtual DbSet<CierreDeCajaDetalle> CierreDeCajaDetalle { get; set; }
    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Compra> Compras { get; set; }
    public virtual DbSet<Comprobante> Comprobante { get; set; }

    public virtual DbSet<CompraDetalle> CompraDetalles { get; set; }
    public virtual DbSet<CompraFormasDePago> CompraFormasDePago { get; set; }

    public virtual DbSet<CuentaCorriente> CuentaCorrientes { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<Gasto> Gasto { get; set; }
    public virtual DbSet<Ingreso> Ingreso { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }
    public virtual DbSet<ProductoEstado> ProductoEstado { get; set; }

    public virtual DbSet<Session> Sessions { get; set; }

    public virtual DbSet<Sucursal> Sucursales { get; set; }
    public virtual DbSet<ParamAfip> ParamAfip { get; set; }


    public virtual DbSet<TipoFormaDePago> TipoFormaDePago { get; set; }

    public virtual DbSet<TipoGasto> TipoGasto { get; set; }
    public virtual DbSet<TipoIngreso> TipoIngreso { get; set; }

    public virtual DbSet<TiposDeMovimiento> TiposDeMovimientos { get; set; }

    public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }

    public virtual DbSet<TipoTalle> TipoTalle { get; set; }

    public virtual DbSet<TipoMarca> TipoMarca { get; set; }

    public virtual DbSet<TiposProducto> TiposProductos { get; set; }

    public virtual DbSet<TipoEstado> TipoEstado { get; set; }
    public virtual DbSet<TablaDeConfiguracion> TablaDeConfiguracion { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<VentaDetalle> VentaDetalles { get; set; }

    public virtual DbSet<VentaFormasDePago> VentaFormasDePagos { get; set; }

    public virtual DbSet<Venta> Venta { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CierreDeCajaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CierreDeCajaDetalleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CompraConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ComprobanteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CompraDetalleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CompraFormasDePagoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CuentaCorrienteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmpleadoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.GastoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.IngresoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductoEstadoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SessionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SucursaleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ParamAfipConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoFormaDePagoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TiposDeGastoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TiposDeIngresoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TiposDeMovimientoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoDocumentoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoTalleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoEstadoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoMarcaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TablaDeConfiguracionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TiposProductoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VentaDetalleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VentaFormasDePagoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VentaConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
