//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a13.soap.ws.server.puc.sr/")]
public partial class SRValidationException
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a13.soap.ws.server.puc.sr/")]
public partial class metadata
{
    
    private System.DateTime fechaHoraField;
    
    private bool fechaHoraFieldSpecified;
    
    private string servidorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public System.DateTime fechaHora
    {
        get
        {
            return this.fechaHoraField;
        }
        set
        {
            this.fechaHoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaHoraSpecified
    {
        get
        {
            return this.fechaHoraFieldSpecified;
        }
        set
        {
            this.fechaHoraFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string servidor
    {
        get
        {
            return this.servidorField;
        }
        set
        {
            this.servidorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a13.soap.ws.server.puc.sr/")]
public partial class idPersonaListReturn
{
    
    private System.Nullable<long>[] idPersonaField;
    
    private metadata metadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
    public System.Nullable<long>[] idPersona
    {
        get
        {
            return this.idPersonaField;
        }
        set
        {
            this.idPersonaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public metadata metadata
    {
        get
        {
            return this.metadataField;
        }
        set
        {
            this.metadataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a13.soap.ws.server.puc.sr/")]
public partial class dummyReturn
{
    
    private string appserverField;
    
    private string authserverField;
    
    private string dbserverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string appserver
    {
        get
        {
            return this.appserverField;
        }
        set
        {
            this.appserverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string authserver
    {
        get
        {
            return this.authserverField;
        }
        set
        {
            this.authserverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string dbserver
    {
        get
        {
            return this.dbserverField;
        }
        set
        {
            this.dbserverField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", ConfigurationName="PersonaServiceA13")]
public interface PersonaServiceA13
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<dummyResponse> dummyAsync(dummy request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(SRValidationException), Action="", Name="SRValidationException")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<getIdPersonaListByDocumentoResponse> getIdPersonaListByDocumentoAsync(getIdPersonaListByDocumento request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(SRValidationException), Action="", Name="SRValidationException")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<getPersonaResponse> getPersonaAsync(getPersona request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="dummy", WrapperNamespace="http://a13.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class dummy
{
    
    public dummy()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="dummyResponse", WrapperNamespace="http://a13.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class dummyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public dummyReturn @return;
    
    public dummyResponse()
    {
    }
    
    public dummyResponse(dummyReturn @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getIdPersonaListByDocumento", WrapperNamespace="http://a13.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getIdPersonaListByDocumento
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sign;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long cuitRepresentada;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string documento;
    
    public getIdPersonaListByDocumento()
    {
    }
    
    public getIdPersonaListByDocumento(string token, string sign, long cuitRepresentada, string documento)
    {
        this.token = token;
        this.sign = sign;
        this.cuitRepresentada = cuitRepresentada;
        this.documento = documento;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getIdPersonaListByDocumentoResponse", WrapperNamespace="http://a13.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getIdPersonaListByDocumentoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public idPersonaListReturn idPersonaListReturn;
    
    public getIdPersonaListByDocumentoResponse()
    {
    }
    
    public getIdPersonaListByDocumentoResponse(idPersonaListReturn idPersonaListReturn)
    {
        this.idPersonaListReturn = idPersonaListReturn;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a13.soap.ws.server.puc.sr/")]
public partial class personaReturn
{
    
    private metadata metadataField;
    
    private persona personaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public metadata metadata
    {
        get
        {
            return this.metadataField;
        }
        set
        {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public persona persona
    {
        get
        {
            return this.personaField;
        }
        set
        {
            this.personaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a13.soap.ws.server.puc.sr/")]
public partial class persona
{
    
    private string apellidoField;
    
    private System.Nullable<long>[] claveInactivaAsociadaField;
    
    private string descripcionActividadPrincipalField;
    
    private domicilio[] domicilioField;
    
    private string estadoClaveField;
    
    private System.DateTime fechaContratoSocialField;
    
    private bool fechaContratoSocialFieldSpecified;
    
    private System.DateTime fechaFallecimientoField;
    
    private bool fechaFallecimientoFieldSpecified;
    
    private System.DateTime fechaNacimientoField;
    
    private bool fechaNacimientoFieldSpecified;
    
    private string formaJuridicaField;
    
    private long idActividadPrincipalField;
    
    private bool idActividadPrincipalFieldSpecified;
    
    private long idPersonaField;
    
    private bool idPersonaFieldSpecified;
    
    private int mesCierreField;
    
    private bool mesCierreFieldSpecified;
    
    private string nombreField;
    
    private string numeroDocumentoField;
    
    private int periodoActividadPrincipalField;
    
    private bool periodoActividadPrincipalFieldSpecified;
    
    private string razonSocialField;
    
    private string tipoClaveField;
    
    private string tipoDocumentoField;
    
    private string tipoPersonaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string apellido
    {
        get
        {
            return this.apellidoField;
        }
        set
        {
            this.apellidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("claveInactivaAsociada", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public System.Nullable<long>[] claveInactivaAsociada
    {
        get
        {
            return this.claveInactivaAsociadaField;
        }
        set
        {
            this.claveInactivaAsociadaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string descripcionActividadPrincipal
    {
        get
        {
            return this.descripcionActividadPrincipalField;
        }
        set
        {
            this.descripcionActividadPrincipalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("domicilio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
    public domicilio[] domicilio
    {
        get
        {
            return this.domicilioField;
        }
        set
        {
            this.domicilioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string estadoClave
    {
        get
        {
            return this.estadoClaveField;
        }
        set
        {
            this.estadoClaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public System.DateTime fechaContratoSocial
    {
        get
        {
            return this.fechaContratoSocialField;
        }
        set
        {
            this.fechaContratoSocialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaContratoSocialSpecified
    {
        get
        {
            return this.fechaContratoSocialFieldSpecified;
        }
        set
        {
            this.fechaContratoSocialFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public System.DateTime fechaFallecimiento
    {
        get
        {
            return this.fechaFallecimientoField;
        }
        set
        {
            this.fechaFallecimientoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaFallecimientoSpecified
    {
        get
        {
            return this.fechaFallecimientoFieldSpecified;
        }
        set
        {
            this.fechaFallecimientoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public System.DateTime fechaNacimiento
    {
        get
        {
            return this.fechaNacimientoField;
        }
        set
        {
            this.fechaNacimientoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaNacimientoSpecified
    {
        get
        {
            return this.fechaNacimientoFieldSpecified;
        }
        set
        {
            this.fechaNacimientoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string formaJuridica
    {
        get
        {
            return this.formaJuridicaField;
        }
        set
        {
            this.formaJuridicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public long idActividadPrincipal
    {
        get
        {
            return this.idActividadPrincipalField;
        }
        set
        {
            this.idActividadPrincipalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idActividadPrincipalSpecified
    {
        get
        {
            return this.idActividadPrincipalFieldSpecified;
        }
        set
        {
            this.idActividadPrincipalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public long idPersona
    {
        get
        {
            return this.idPersonaField;
        }
        set
        {
            this.idPersonaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idPersonaSpecified
    {
        get
        {
            return this.idPersonaFieldSpecified;
        }
        set
        {
            this.idPersonaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public int mesCierre
    {
        get
        {
            return this.mesCierreField;
        }
        set
        {
            this.mesCierreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mesCierreSpecified
    {
        get
        {
            return this.mesCierreFieldSpecified;
        }
        set
        {
            this.mesCierreFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string nombre
    {
        get
        {
            return this.nombreField;
        }
        set
        {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string numeroDocumento
    {
        get
        {
            return this.numeroDocumentoField;
        }
        set
        {
            this.numeroDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public int periodoActividadPrincipal
    {
        get
        {
            return this.periodoActividadPrincipalField;
        }
        set
        {
            this.periodoActividadPrincipalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodoActividadPrincipalSpecified
    {
        get
        {
            return this.periodoActividadPrincipalFieldSpecified;
        }
        set
        {
            this.periodoActividadPrincipalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
    public string razonSocial
    {
        get
        {
            return this.razonSocialField;
        }
        set
        {
            this.razonSocialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
    public string tipoClave
    {
        get
        {
            return this.tipoClaveField;
        }
        set
        {
            this.tipoClaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
    public string tipoDocumento
    {
        get
        {
            return this.tipoDocumentoField;
        }
        set
        {
            this.tipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
    public string tipoPersona
    {
        get
        {
            return this.tipoPersonaField;
        }
        set
        {
            this.tipoPersonaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a13.soap.ws.server.puc.sr/")]
public partial class domicilio
{
    
    private string calleField;
    
    private string codigoPostalField;
    
    private string datoAdicionalField;
    
    private string descripcionProvinciaField;
    
    private string direccionField;
    
    private string estadoDomicilioField;
    
    private int idProvinciaField;
    
    private bool idProvinciaFieldSpecified;
    
    private string localidadField;
    
    private string manzanaField;
    
    private int numeroField;
    
    private bool numeroFieldSpecified;
    
    private string oficinaDptoLocalField;
    
    private string pisoField;
    
    private string sectorField;
    
    private string tipoDatoAdicionalField;
    
    private string tipoDomicilioField;
    
    private string torreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string calle
    {
        get
        {
            return this.calleField;
        }
        set
        {
            this.calleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string codigoPostal
    {
        get
        {
            return this.codigoPostalField;
        }
        set
        {
            this.codigoPostalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string datoAdicional
    {
        get
        {
            return this.datoAdicionalField;
        }
        set
        {
            this.datoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string descripcionProvincia
    {
        get
        {
            return this.descripcionProvinciaField;
        }
        set
        {
            this.descripcionProvinciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string direccion
    {
        get
        {
            return this.direccionField;
        }
        set
        {
            this.direccionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string estadoDomicilio
    {
        get
        {
            return this.estadoDomicilioField;
        }
        set
        {
            this.estadoDomicilioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public int idProvincia
    {
        get
        {
            return this.idProvinciaField;
        }
        set
        {
            this.idProvinciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idProvinciaSpecified
    {
        get
        {
            return this.idProvinciaFieldSpecified;
        }
        set
        {
            this.idProvinciaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string localidad
    {
        get
        {
            return this.localidadField;
        }
        set
        {
            this.localidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string manzana
    {
        get
        {
            return this.manzanaField;
        }
        set
        {
            this.manzanaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public int numero
    {
        get
        {
            return this.numeroField;
        }
        set
        {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numeroSpecified
    {
        get
        {
            return this.numeroFieldSpecified;
        }
        set
        {
            this.numeroFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string oficinaDptoLocal
    {
        get
        {
            return this.oficinaDptoLocalField;
        }
        set
        {
            this.oficinaDptoLocalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string piso
    {
        get
        {
            return this.pisoField;
        }
        set
        {
            this.pisoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string sector
    {
        get
        {
            return this.sectorField;
        }
        set
        {
            this.sectorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string tipoDatoAdicional
    {
        get
        {
            return this.tipoDatoAdicionalField;
        }
        set
        {
            this.tipoDatoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public string tipoDomicilio
    {
        get
        {
            return this.tipoDomicilioField;
        }
        set
        {
            this.tipoDomicilioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
    public string torre
    {
        get
        {
            return this.torreField;
        }
        set
        {
            this.torreField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersona", WrapperNamespace="http://a13.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersona
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sign;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long cuitRepresentada;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long idPersona;
    
    public getPersona()
    {
    }
    
    public getPersona(string token, string sign, long cuitRepresentada, long idPersona)
    {
        this.token = token;
        this.sign = sign;
        this.cuitRepresentada = cuitRepresentada;
        this.idPersona = idPersona;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaResponse", WrapperNamespace="http://a13.soap.ws.server.puc.sr/", IsWrapped=true)]
public partial class getPersonaResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a13.soap.ws.server.puc.sr/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public personaReturn personaReturn;
    
    public getPersonaResponse()
    {
    }
    
    public getPersonaResponse(personaReturn personaReturn)
    {
        this.personaReturn = personaReturn;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface PersonaServiceA13Channel : PersonaServiceA13, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class PersonaServiceA13Client : System.ServiceModel.ClientBase<PersonaServiceA13>, PersonaServiceA13
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public PersonaServiceA13Client() : 
            base(PersonaServiceA13Client.GetDefaultBinding(), PersonaServiceA13Client.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.PersonaServiceA13Port.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA13Client(EndpointConfiguration endpointConfiguration) : 
            base(PersonaServiceA13Client.GetBindingForEndpoint(endpointConfiguration), PersonaServiceA13Client.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA13Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(PersonaServiceA13Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA13Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(PersonaServiceA13Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public PersonaServiceA13Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<dummyResponse> PersonaServiceA13.dummyAsync(dummy request)
    {
        return base.Channel.dummyAsync(request);
    }
    
    public System.Threading.Tasks.Task<dummyResponse> dummyAsync()
    {
        dummy inValue = new dummy();
        return ((PersonaServiceA13)(this)).dummyAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getIdPersonaListByDocumentoResponse> PersonaServiceA13.getIdPersonaListByDocumentoAsync(getIdPersonaListByDocumento request)
    {
        return base.Channel.getIdPersonaListByDocumentoAsync(request);
    }
    
    public System.Threading.Tasks.Task<getIdPersonaListByDocumentoResponse> getIdPersonaListByDocumentoAsync(string token, string sign, long cuitRepresentada, string documento)
    {
        getIdPersonaListByDocumento inValue = new getIdPersonaListByDocumento();
        inValue.token = token;
        inValue.sign = sign;
        inValue.cuitRepresentada = cuitRepresentada;
        inValue.documento = documento;
        return ((PersonaServiceA13)(this)).getIdPersonaListByDocumentoAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getPersonaResponse> PersonaServiceA13.getPersonaAsync(getPersona request)
    {
        return base.Channel.getPersonaAsync(request);
    }
    
    public System.Threading.Tasks.Task<getPersonaResponse> getPersonaAsync(string token, string sign, long cuitRepresentada, long idPersona)
    {
        getPersona inValue = new getPersona();
        inValue.token = token;
        inValue.sign = sign;
        inValue.cuitRepresentada = cuitRepresentada;
        inValue.idPersona = idPersona;
        return ((PersonaServiceA13)(this)).getPersonaAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PersonaServiceA13Port))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PersonaServiceA13Port))
        {
            return new System.ServiceModel.EndpointAddress("https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA13");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return PersonaServiceA13Client.GetBindingForEndpoint(EndpointConfiguration.PersonaServiceA13Port);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return PersonaServiceA13Client.GetEndpointAddress(EndpointConfiguration.PersonaServiceA13Port);
    }
    
    public enum EndpointConfiguration
    {
        
        PersonaServiceA13Port,
    }
}
