// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities.Items;

[PrimaryKey("IdCierre", "IdDetalle")]
[Table("CierreDeCajaDetalle")]
public partial class CierreDeCajaDetalle
{
    [Key]
    public long IdDetalle { get; set; }
    [Key]
    public long IdCierre { get; set; }
    public int IdTipoFormaPago { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal Total { get; set; }


    [ForeignKey("IdCierre")]
    [InverseProperty("CierreDeCajaDetalle")]
    public virtual CierreDeCaja IdCierreNavigation { get; set; }

    [ForeignKey("IdTipoFormaPago")]
    [InverseProperty("CierreDeCajaDetalle")]
    public virtual TipoFormaDePago IdTipoFormaPagoNavigation { get; set; }
}