// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities.Items
{

    public partial class Cliente
    {
        [Key]
        public int IdCliente { get; set; }

        [Required]
        [StringLength(100)]
        public string Nombre { get; set; }

        [Required]
        [StringLength(100)]
        public string Apellido { get; set; }

        [Required]
        [StringLength(100)]
        public string Mail { get; set; }

        [Required]
        [StringLength(11)]
        public string NroDocumento { get; set; }

        public int IdTipoDocumento { get; set; }
        
        [Column(TypeName = "numeric(18, 2)")]
        public decimal SaldoEnCuenta { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }

        public int? IdUsuario { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();

        [ForeignKey("IdUsuario")]
        [InverseProperty("Clientes")]
        public virtual Usuario IdUsuarioNavigation { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();
    }
}