// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[PrimaryKey("IdCompra", "IdProducto")]
[Table("CompraDetalle")]
public partial class CompraDetalle
{
    [Key]
    public long IdCompra { get; set; }

    [Key]
    public long IdProducto { get; set; }

    public int Cantidad { get; set; }

    [Column(TypeName = "numeric(18, 2)")]

    [ForeignKey("IdCompra")]
    [InverseProperty("CompraDetalles")]
    public virtual Compra IdCompraNavigation { get; set; }

    [ForeignKey("IdProducto")]
    [InverseProperty("CompraDetalles")]
    public virtual Producto IdProductoNavigation { get; set; }
}