// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities.Items;

public partial class Compra
{
    [Key]
    public long IdCompra { get; set; }

    public int IdSucursal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaCompra { get; set; }

    public int IdCliente { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal TotalDeCompra { get; set; }
    [Column(TypeName = "numeric(18, 2)")]
    public decimal TotalCreditoEnTienda { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    public int IdUsuario { get; set; }

    [InverseProperty("IdCompraNavigation")]
    public virtual ICollection<CompraDetalle> CompraDetalles { get; set; } = new List<CompraDetalle>();    
    
    [InverseProperty("IdCompraNavigation")]
    public virtual ICollection<CompraFormasDePago> CompraFormasDePago { get; set; } = new List<CompraFormasDePago>();

    [ForeignKey("IdCliente")]
    [InverseProperty("Compras")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdSucursal")]
    [InverseProperty("Compras")]
    public virtual Sucursal IdSucursalNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Compras")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}