// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[PrimaryKey("IdCompra", "IdTipoFormaPago")]
[Table("ComprasFormasDePago")]
public partial class CompraFormasDePago
{
    [Key]
    public long IdCompra { get; set; }

    [Key]
    public int IdTipoFormaPago { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal Valor { get; set; }

    [ForeignKey("IdTipoFormaPago")]
    [InverseProperty("CompraFormasDePago")]
    public virtual TipoFormaDePago IdTipoFormaPagoNavigation { get; set; }

    [ForeignKey("IdCompra")]
    [InverseProperty("CompraFormasDePago")]
    public virtual Compra IdCompraNavigation { get; set; }
}