// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[Table("CuentaCorriente")]
public partial class CuentaCorriente
{
    [Key]
    public long IdCtacte { get; set; }

    public int IdSucursal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    public long IdMovimiento { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal Importe { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal SaldoActual { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string IdTipoDeMovimiento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    public long? IdCierre { get; set; }

    [ForeignKey("IdCierre")]
    [InverseProperty("CuentaCorrientes")]
    public virtual CierreDeCaja IdCierreNavigation { get; set; }

    [ForeignKey("IdSucursal")]
    [InverseProperty("CuentaCorrientes")]
    public virtual Sucursal IdSucursalNavigation { get; set; }

    [ForeignKey("IdTipoDeMovimiento")]
    [InverseProperty("CuentaCorrientes")]
    public virtual TiposDeMovimiento IdTipoDeMovimientoNavigation { get; set; }
}