// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

public partial class Empleado
{
    [Key]
    public int IdEmpleado { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Apellido { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaNacimiento { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Direccion { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Telefono { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Activo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    [InverseProperty("IdEmpleadoNavigation")]
    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}