// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;
[Table("Gasto")]
public partial class Gasto
{
    [Key]
    [Column("IdGasto")]
    public long Id { get; set; }

    public int IdSucursal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal Importe { get; set; }
    
    [Column("IdTipoDeGasto")]
    public int IdTipoDeGasto { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }
    public string Descripcion { get; set; }

    public int IdUsuario { get; set; }
    public int IdTipoFormaPago { get; set; }

    [ForeignKey("IdSucursal")]
    [InverseProperty("Gasto")]
    public virtual Sucursal IdSucursalNavigation { get; set; }

    [ForeignKey("IdTipoDeGasto")]
    [InverseProperty("Gasto")]
    public virtual TipoGasto IdTipoDeGastoNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Gasto")]
    public virtual Usuario IdUsuarioNavigation { get; set; }    
    
    [ForeignKey("IdTipoFormaPago")]
    [InverseProperty("Gasto")]
    public virtual TipoFormaDePago IdTipoFormaPagoNavigation { get; set; }
}