// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

public partial class Producto
{
    [Key]
    public long IdProducto { get; set; }

    public int IdEstado { get; set; }

    //[StringLength(50)]
    //[Unicode(false)]
    //public string Descripcion { get; set; }

    public int Stock { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal PrecioDeCompra { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal PrecioDeVenta { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    public int IdUsuario { get; set; }

    public int IdTipoProducto { get; set; }
    public int IdTipoMarca { get; set; }
    public int IdTipoTalle { get; set; }

    [InverseProperty("IdProductoNavigation")]
    public virtual ICollection<CompraDetalle> CompraDetalles { get; set; } = new List<CompraDetalle>();

    [InverseProperty("IdProductoNavigation")]
    public virtual ICollection<VentaDetalle> VentaDetalles { get; set; } = new List<VentaDetalle>();

    [InverseProperty("IdProductoNavigation")]
    public virtual ICollection<ProductoEstado> ProductoEstado { get; set; } = new List<ProductoEstado>();

    [ForeignKey("IdEstado")]
    [InverseProperty("Productos")]
    public virtual TipoEstado IdEstadoNavigation { get; set; }

    [ForeignKey("IdTipoProducto")]
    [InverseProperty("Productos")]
    public virtual TiposProducto IdTipoProductoNavigation { get; set; }

    [ForeignKey("IdTipoMarca")]
    [InverseProperty("Productos")]
    public virtual TipoMarca IdTipoMarcaNavigation { get; set; }

    [ForeignKey("IdTipoTalle")]
    [InverseProperty("Productos")]
    public virtual TipoTalle IdTipoTalleNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Productos")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}