// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[Table("ProductoEstado")]
public partial class ProductoEstado
{
    [Key]
    public long Id { get; set; }

    public long IdProducto { get; set; }

    public int IdEstado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaFin { get; set; }

    public int IdUsuario { get; set; }

    [ForeignKey("IdEstado")]
    [InverseProperty("ProductoEstado")]
    public virtual TipoEstado IdEstadoNavigation { get; set; }

    [ForeignKey("IdProducto")]
    [InverseProperty("ProductoEstado")]
    public virtual Producto IdProductoNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("ProductoEstado")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}