// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

public partial class Session
{
    [Key]
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OpenedAt { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Sessions")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}