// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

public partial class Sucursal
{
    [Key]
    public int IdSucursal { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Direccion { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Telefono { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Activo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<CierreDeCaja> CierreDeCaja { get; set; } = new List<CierreDeCaja>();

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<CuentaCorriente> CuentaCorrientes { get; set; } = new List<CuentaCorriente>();

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<Gasto> Gasto { get; set; } = new List<Gasto>();
    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<Ingreso> Ingreso { get; set; } = new List<Ingreso>();

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();

    [InverseProperty("IdSucursalNavigation")]
    public virtual ICollection<TablaDeConfiguracion> TablaDeConfiguracion { get; set; } = new List<TablaDeConfiguracion>();

    [InverseProperty("SucursalNavigation")]
    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();
}