// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Entities.Items;

[Table("TablaDeConfiguracion")]
public partial class TablaDeConfiguracion
{
    [Key]
    public int IdConfiguracion { get; set; }
    public int IdSucursal { get; set; }

    [StringLength(10)]
    public string Clave { get; set; }  
    
    [StringLength(50)]
    public string Descripcion { get; set; }

    [StringLength(100)]
    public string ValorString { get; set; }
    public bool? ValorBool { get; set; }
    public decimal? ValorDecimal { get; set; }
    public int? ValorInteger { get; set; }

    [ForeignKey("IdSucursal")]
    [InverseProperty("TablaDeConfiguracion")]
    public virtual Sucursal IdSucursalNavigation { get; set; }
}
