// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[Table("TipoFormasDePago")]
public partial class TipoFormaDePago
{
    [Key]
    [Column("IdTipoFormaPago")]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Activo { get; set; }

    [Column(TypeName = "numeric(3, 2)")]
    public decimal? Descuento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }
    public int IdUsuario { get; set; }

    [InverseProperty("IdTipoFormaPagoNavigation")]
    public virtual ICollection<CompraFormasDePago> CompraFormasDePago { get; set; } = new List<CompraFormasDePago>();

    [InverseProperty("IdTipoFormaPagoNavigation")]
    public virtual ICollection<CierreDeCajaDetalle> CierreDeCajaDetalle { get; set; } = new List<CierreDeCajaDetalle>();

    [InverseProperty("IdTipoFormaPagoNavigation")]
    public virtual ICollection<VentaFormasDePago> VentaFormasDePagos { get; set; } = new List<VentaFormasDePago>(); 
    
    [InverseProperty("IdTipoFormaPagoNavigation")]
    public virtual ICollection<Gasto> Gasto { get; set; } = new List<Gasto>();

    [InverseProperty("IdTipoFormaPagoNavigation")]
    public virtual ICollection<Ingreso> Ingreso { get; set; } = new List<Ingreso>();

    [ForeignKey("IdUsuario")]
    [InverseProperty("TipoFormasDePago")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}