// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[Table("TiposDeMovimiento")]
public partial class TiposDeMovimiento
{
    [Key]
    [StringLength(1)]
    [Unicode(false)]
    public string IdTipoDeMovimiento { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Activo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    [InverseProperty("IdTipoDeMovimientoNavigation")]
    public virtual ICollection<CuentaCorriente> CuentaCorrientes { get; set; } = new List<CuentaCorriente>();
}