// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[Index("NombreUsuario", Name = "UQ_Usuario", IsUnique = true)]
public partial class Usuario
{
    [Key]
    public int IdUsuario { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string NombreUsuario { get; set; }

    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string Contraseña { get; set; }

    public int? IdEmpleado { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Activo { get; set; }

    [StringLength(2048)]
    public string token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Gasto> Gasto { get; set; } = new List<Gasto>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Ingreso> Ingreso { get; set; } = new List<Ingreso>();

    [ForeignKey("IdEmpleado")]
    [InverseProperty("Usuarios")]
    public virtual Empleado IdEmpleadoNavigation { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<CierreDeCaja> CierreDeCaja { get; set; } = new List<CierreDeCaja>();  
    
    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Producto> Productos { get; set; } = new List<Producto>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<ProductoEstado> ProductoEstado { get; set; } = new List<ProductoEstado>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TipoGasto> TipoGasto { get; set; } = new List<TipoGasto>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TipoIngreso> TipoIngreso { get; set; } = new List<TipoIngreso>();  
    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TipoEstado> TipoEstado { get; set; } = new List<TipoEstado>();

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TipoMarca> TipoMarca { get; set; } = new List<TipoMarca>();
    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TipoTalle> TipoTalle { get; set; } = new List<TipoTalle>(); 
    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TiposProducto> TiposProducto { get; set; } = new List<TiposProducto>();   
    
    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TipoFormaDePago> TipoFormasDePago { get; set; } = new List<TipoFormaDePago>();
    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<TipoDocumento> TipoDocumento { get; set; } = new List<TipoDocumento>();

    // Navigation property to Comprobante
    [InverseProperty("UsuarioNavigation")]
    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();
}