// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[PrimaryKey("IdVenta", "IdProducto")]
[Table("VentaDetalle")]
public partial class VentaDetalle
{
    [Key]
    public long IdVenta { get; set; }

    [Key]
    public long IdProducto { get; set; }

    public int Cantidad { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal Valor { get; set; }

    [ForeignKey("IdProducto")]
    [InverseProperty("VentaDetalles")]
    public virtual Producto IdProductoNavigation { get; set; }

    [ForeignKey("IdVenta")]
    [InverseProperty("VentaDetalles")]
    public virtual Venta IdVentaNavigation { get; set; }
}