// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

[PrimaryKey("IdVenta", "IdTipoFormaPago")]
[Table("VentaFormasDePago")]
public partial class VentaFormasDePago
{
    [Key]
    public long IdVenta { get; set; }

    [Key]
    public int IdTipoFormaPago { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal ValorParcial { get; set; }

    [ForeignKey("IdTipoFormaPago")]
    [InverseProperty("VentaFormasDePagos")]
    public virtual TipoFormaDePago IdTipoFormaPagoNavigation { get; set; }

    [ForeignKey("IdVenta")]
    [InverseProperty("VentaFormasDePagos")]
    public virtual Venta IdVentaNavigation { get; set; }
}