// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Items;

public partial class Venta
{
    [Key]
    public long IdVenta { get; set; }

    public int IdSucursal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaVenta { get; set; }

    public int? IdCliente { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal TotalDeVenta { get; set; }

    public long? IdComprobante { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    public int? IdUsuario { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("Venta")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdSucursal")]
    [InverseProperty("Venta")]
    public virtual Sucursal IdSucursalNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Venta")]
    public virtual Usuario IdUsuarioNavigation { get; set; }  
    
    [ForeignKey("IdComprobante")]
    [InverseProperty("Venta")]
    public virtual Comprobante IdComprobanteNavigation { get; set; }

    [InverseProperty("IdVentaNavigation")]
    public virtual ICollection<VentaDetalle> VentaDetalles { get; set; } = new List<VentaDetalle>();

    [InverseProperty("IdVentaNavigation")]
    public virtual ICollection<VentaFormasDePago> VentaFormasDePagos { get; set; } = new List<VentaFormasDePago>();
}